config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'pages#home'
  get 'about' => 'pages#about'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  def index
    @pins = Pin.all
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
      if @pin.save
        redirect_to @pin, notice: 'Pin was successfully created.'
      else
        render :new
      end
  end

  def update
      if @pin.update(pin_params)
        redirect_to @pin, notice: 'Pin was successfully updated.'
      else
        render :edit 
      end
  end

  def destroy
    @pin.destroy
      redirect_to pins_url, notice: 'Pin was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

     def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pinteresting",root_path,class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">  
      <ul class="nav navbar-nav navbar-right">

        <li> <%= link_to "Home",root_path %> </li>
        <li> <%= link_to "About",about_path %> </li>
        <% if user_signed_in? %>
        <li> <%= link_to "Account Settings",edit_user_registration_path %> </li>
          <li> <%= link_to "Log out",destroy_user_session_path, method: :delete %> </li>
        <% else %>
          <li> <%= link_to "Sign in",new_user_session_path %> </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<%= render"layouts/header" %>
	<div class="container">
		<% flash.each do |name,msg| %>
			<%= content_tag(:div,msg,class:"alert alert-success") %>
		<% end %>
		<%= yield %>	
	</div>
	

</body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
	<h1>Welcome to our app!</h1>
	
	<% if user_signed_in? %>
		<%= link_to "Pins",pins_path, class:"btn btn-primary btn-lg" %> 
	<% else %>
		<p>
			<%= link_to "Log in",new_user_session_path ,class:"btn btn-default btn-lg"%>
			<%= link_to "Sign up",new_user_registration_path,class:"btn btn-success btn-lg" %>
		</p>
	<% end %>
</div>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pins</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.description %></td>
        <td><%= pin.user_id %></td>
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>